name: reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        default: dist
        type: string
    secrets:
      some-secret:
        required: false
jobs:
  deploy_r:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: output info
        env:
          MY_SECRET: ${{ secrets.some-secret }}
        run: echo "deploy...............< ${{ secrets.some-secret }} (${#MY_SECRET} symbols)"

